/* Implement linear unfold function that returns a sequence that contains the elements generated by the given computation:
F(callback, initialValue)
callback: A function that takes the current state and returns a tupleconsisting ofthe next element of the sequence and the next state value.
Callback accepts current value and produces new state and element.Unfold stops upon falsy value returned by callback.
initialValue: The initial state value.*/
 
function linearUnfold(callback, initialValue) {
    let arr = [],//создаем пустой массив 
        state = initialValue,//присваиваем в состояние переданное в ф-цию значение 
        value;
    while (state !== null) { //пока состояние не ноль, 
        [state, value] = callback(initialValue);//вызываем колбэк функцию 
        arr.push(value);//пушим значение в массив 
    }
    console.log(arr);
    return arr; //возвращаем массив как результат
}
 
function funcWithRandomValue(state) { //колбэк ф-ция которая принимает в качестве аргумента состояние
    //console.log(state);
    let value = Math.floor(Math.random() * 10);//значения создаем рандомно
    console.log(value);//
    if (value >= 5) {
        state = null;
    }
    console.log([
        state,
        value
    ])
    return [
        state,
        value
    ]
}

let result = linearUnfold(funcWithRandomValue, 1);
alert (result);